trigger:
- main

pool:
  name: custompool1

stages:
- stage: Test
  jobs:
  - job: RunTests
    steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '3.13'
      displayName: 'Use Python 3.13'
    
    - script: pip install poetry
      displayName: 'Install Poetry'
    
    - script: poetry install
      displayName: 'Install Dependencies'
    
    - script: poetry run pytest -v
      displayName: 'Run Tests'
