trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: Test
  jobs:
  - job: RunTests
    steps:
    - script: python3 --version
      displayName: 'Check Python Version'
    
    - script: sudo apt-get update && sudo apt-get install -y python3-pip
      displayName: 'Install pip'
    
    - script: python3 -m pip install poetry
      displayName: 'Install Poetry'
    
    - script: python3 -m poetry install
      displayName: 'Install Dependencies'
    
    - script: python3 -m poetry run pytest -v
      displayName: 'Run Tests'
