trigger:
- main

pool:
  name: custompool1

stages:
- stage: Test
  jobs:
  - job: RunTests
    steps:
    - script: python3 --version
      displayName: 'Check Python Version'

    - script: python3 -m ensurepip --upgrade
      displayName: 'Ensure pip is installed'
    
    - script: python3 -m pip install poetry
      displayName: 'Install Poetry'
    
    - script: poetry install
      displayName: 'Install Dependencies'
    
    - script: poetry run pytest -v
      displayName: 'Run Tests'
