trigger:
- main

pool:
  name: custompool1

stages:
- stage: Test
  jobs:
  - job: RunTests
    steps:
    - script: python --version
      displayName: 'Check Python Version'
    
    - script: pip install poetry
      displayName: 'Install Poetry'
    
    - script: poetry install
      displayName: 'Install Dependencies'
    
    - script: poetry run pytest -v
      displayName: 'Run Tests'
